### ISSUE TITLE
Error segmented_slc55

### ISSUE THREAD

**Issue by mohp1-data** [bingogome/samm#32]
Hi,
I am getting this error: 
ERROR:root:Traceback (most recent call last):
  File "C:\Users\mohpe\samm\samm-python-terminal\sam_server.py", line 272, in main
    srv.infer_image( \
  File "C:\Users\mohpe\samm\samm-python-terminal\sam_server.py", line 183, in infer_image
    self.load_feature(os.path.join(self.workspace, "segmented_images", "segmented_" + image_name + ".pkl"))
  File "C:\Users\mohpe\samm\samm-python-terminal\sam_server.py", line 165, in load_feature
    with open(self.feature_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mohpe\\samm\\samm-python-terminal\\samm-workspace\\segmented_images\\segmented_slc55.pkl'

**Comment by bingogome** [comment]
Could you refer to this issue #31 to see if it's relevant?

**Comment by mohp1-data** [comment]
I clicked compute embedding and I am getting this error in python console:
Traceback (most recent call last):
  File "C:\Users\mohpe\samm\samm\SammBase\SammBaseLib\LogicSamm.py", line 217, in processStartMaskSync
    self._segNumpy[curslc,:,:] = memmap.astype(int)
IndexError: index 112 is out of bounds for axis 0 with size 112

**Comment by bingogome** [comment]
It's hard to reproduce the error on my side. Would you be interested in a Zoom meeting? Shoot me an email at yliu333@jhu.edu

**Comment by bingogome** [comment]
Met and reproduced with VRAM not nought
