### ISSUE TITLE
fileNotFoundError

### ISSUE THREAD

**Issue by empat6** [bingogome/samm#44]
Please help... why i got this error?

Traceback (most recent call last):
  File "C:\Users\zaril\samm\samm\SammBase\SammBaseLib\WidgetSammBase.py", line 141, in onPushStartMaskSync
    self.logic.processStartMaskSync()
  File "C:\Users\zaril\samm\samm\SammBase\SammBaseLib\LogicSamm.py", line 209, in processStartMaskSync
    memmap = numpy.memmap(self._parameterNode._workspace + '/mask.memmap', \
  File "C:\Users\zaril\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\site-packages\numpy\core\memmap.py", line 228, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zaril\\samm\\samm-python-terminal\\samm-workspace/mask.memmap'

**Comment by sophia303v** [comment]
I encountered the same issue. How did you solve it?

**Comment by kadireker** [comment]
i ve same issue please help. Is there any solution?

**Comment by bingogome** [comment]
This issue should be fixed now in https://github.com/bingogome/samm/commit/5b63c7dfa120c39066215fb766f8b246be3e2414 by switching communication from memory mapping to ZMQ.
