### ISSUE TITLE
How to install pycocotools?

### ISSUE THREAD

**Issue by dzenanz** [bingogome/samm#6]
`slicer.util.pip_install("pycocotools")` does not work on my computer:
```log
Collecting pycocotools
  Using cached pycocotools-2.0.6.tar.gz (24 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from pycocotools) (1.24.2)
Requirement already satisfied: matplotlib>=2.1.0 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from pycocotools) (3.7.1)
Requirement already satisfied: cycler>=0.10 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (0.11.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (4.39.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (5.12.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (9.4.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (1.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from matplotlib>=2.1.0->pycocotools) (23.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from importlib-resources>=3.2.0->matplotlib>=2.1.0->pycocotools) (3.15.0)
Requirement already satisfied: six>=1.5 in c:\users\dzenan\appdata\local\slicer.org\slicer 5.3.0-2023-03-22\lib\python\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools) (1.16.0)
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (pyproject.toml): started
  Building wheel for pycocotools (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\pycocotools
      copying pycocotools\coco.py -> build\lib.win-amd64-cpython-39\pycocotools
      copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-39\pycocotools
      copying pycocotools\mask.py -> build\lib.win-amd64-cpython-39\pycocotools
      copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-39\pycocotools
      running build_ext
      cythoning pycocotools/_mask.pyx to pycocotools\_mask.c
      C:\Temp\User\pip-build-env-a4jsw0mk\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Temp\User\pip-install-6zi08l0e\pycocotools_bbbe4e8b65844fe685ac9309d20a72fc\pycocotools\_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'pycocotools._mask' extension
      creating build\temp.win-amd64-cpython-39
      creating build\temp.win-amd64-cpython-39\Release
      creating build\temp.win-amd64-cpython-39\Release\common
      creating build\temp.win-amd64-cpython-39\Release\pycocotools
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Temp\User\pip-build-env-a4jsw0mk\overlay\Lib\site-packages\numpy\core\include -I./common "-IC:\Users\Dzenan\AppData\Local\slicer.org\Slicer 5.3.0-2023-03-22\lib\Python\include" "-IC:\Users\Dzenan\AppData\Local\slicer.org\Slicer 5.3.0-2023-03-22\lib\Python\Include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tc./common/maskApi.c /Fobuild\temp.win-amd64-cpython-39\Release\./common/maskApi.obj
      maskApi.c
      ./common/maskApi.c(151): warning C4101: 'xp': unreferenced local variable
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Temp\User\pip-build-env-a4jsw0mk\overlay\Lib\site-packages\numpy\core\include -I./common "-IC:\Users\Dzenan\AppData\Local\slicer.org\Slicer 5.3.0-2023-03-22\lib\Python\include" "-IC:\Users\Dzenan\AppData\Local\slicer.org\Slicer 5.3.0-2023-03-22\lib\Python\Include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcpycocotools\_mask.c /Fobuild\temp.win-amd64-cpython-39\Release\pycocotools\_mask.obj
      _mask.c
      pycocotools\_mask.c(6): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Dzenan\AppData\Local\slicer.org\Slicer 5.3.0-2023-03-22\bin\Python\slicer\util.py", line 3586, in pip_install
    _executePythonModule('pip', args)
  File "C:\Users\Dzenan\AppData\Local\slicer.org\Slicer 5.3.0-2023-03-22\bin\Python\slicer\util.py", line 3548, in _executePythonModule
    logProcessOutput(proc)
  File "C:\Users\Dzenan\AppData\Local\slicer.org\Slicer 5.3.0-2023-03-22\bin\Python\slicer\util.py", line 3517, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/Users/Dzenan/AppData/Local/slicer.org/Slicer 5.3.0-2023-03-22/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'pycocotools']' returned non-zero exit status 1.
```
I was able to install it in another virtual environment.

**Comment by bingogome** [comment]
Please refer to the "TLDR version" section in readme.md. Sorry for the inconvenience from the initial unpolished version.
