### ISSUE TITLE
Work Space config.yaml

### ISSUE THREAD

**Issue by chz31** [bingogome/samm#9]
Hi,

I was trying the package and appeared to set up the config.yaml in the Work Space wrong. My Slicer reported the errors after running the embedding:

```
Traceback (most recent call last):
  File "C:\Users\czhan2\Desktop\SAM\samm\samm\SammBase\SammBaseLib\WidgetSammBase.py", line 112, in onPushStartMaskSync
    self.logic.processStartMaskSync()
  File "C:\Users\czhan2\Desktop\SAM\samm\samm\SammBase\SammBaseLib\LogicSamm.py", line 137, in processStartMaskSync
    memmap = numpy.memmap(self._parameterNode._workspace + '/mask.memmap', \
  File "C:\Users\czhan2\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\site-packages\numpy\core\memmap.py", line 228, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\czhan2\\.continuum\\anaconda-client/mask.memmap'
Traceback (most recent call last):
  File "C:\Users\czhan2\Desktop\SAM\samm\samm\SammBase\SammBaseLib\WidgetSammBase.py", line 112, in onPushStartMaskSync
    self.logic.processStartMaskSync()
  File "C:\Users\czhan2\Desktop\SAM\samm\samm\SammBase\SammBaseLib\LogicSamm.py", line 137, in processStartMaskSync
    memmap = numpy.memmap(self._parameterNode._workspace + '/mask.memmap', \
  File "C:\Users\czhan2\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\site-packages\numpy\core\memmap.py", line 228, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\czhan2\\.continuum\\anaconda-client/mask.memmap'
Traceback (most recent call last):
  File "C:\Users\czhan2\Desktop\SAM\samm\samm\SammBase\SammBaseLib\WidgetSammBase.py", line 112, in onPushStartMaskSync
    self.logic.processStartMaskSync()
  File "C:\Users\czhan2\Desktop\SAM\samm\samm\SammBase\SammBaseLib\LogicSamm.py", line 137, in processStartMaskSync
    memmap = numpy.memmap(self._parameterNode._workspace + '/mask.memmap', \
  File "C:\Users\czhan2\AppData\Local\NA-MIC\Slicer 5.2.2\lib\Python\Lib\site-packages\numpy\core\memmap.py", line 228, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\czhan2\\.continuum\\anaconda-client/mask.memmap'
```

Can you give me some suggestions about how to located the proper config.yaml?

Thank you very much!

**Comment by bingogome** [comment]
Hi, thanks for trying it out. The readme was just updated (2 minutes ago). On my test environment, the TLDR instruction worked well.

**Comment by chz31** [comment]
Thank you very much for the update. I did get the error missing "sam_vit_h_4b8939.pth". Can you let me know where I can find "segment-anything/notebooks/sam_vit_h_4b8939.pth"?

**Comment by bingogome** [comment]
https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth
